spring:
  application:
    name: ticketing

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ticketing_db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.yh.ticketing: debug


# 외부에서 /actuator/prometheus 주소로 메트릭을 읽어갈 수 있도록 설정해줌
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}